### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 3136: illegal multibyte sequence

### ISSUE THREAD

**Issue by 1848798517** [JRC1995/Abstractive-Summarization#11]
It has always showed the error.Could you help me solve it?
  File "summarization_model.py", line 24, in <module>
    vocab,embd = loadGloVe(filename)
  File "summarization_model.py", line 16, in loadGloVe
    for line in file.readlines():
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 3136: illegal multibyte sequence

**Comment by JRC1995** [comment]
Are you loading the same glove file or some other embedding file?
It may have something to do with the embedding file that you are loading. 

may be try using 'rb' in place of 'r' in file = open(filename,'r')

https://stackoverflow.com/questions/6320415/unicodedecodeerror-gbk-codec-cant-decode-bytes
https://stackoverflow.com/questions/28165639/unicodedecodeerror-gbk-codec-cant-decode-byte-0x80-in-position-0-illegal-mult

**Comment by 1848798517** [comment]
Thank you very much！Is it available for me to get the paper of this research？

**Comment by JRC1995** [comment]
It wasn't research. I just did it a long time ago to learn stuff. 
However, the basic idea is based on seq2seq model: https://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf

Other relevant papers used to create the model is:
(1) Local attention: https://nlp.stanford.edu/pubs/emnlp15_attn.pdf
(2) RRA: https://arxiv.org/pdf/1709.03714.pdf (not sure if this really helps. Not sure if this paper ever got peer review or something)

These days, it is also standard practice to use pointer networks for this kind of things (even though this project doesn't use it):
https://nlp.stanford.edu/pubs/see2017get.pdf

**Comment by 1848798517** [comment]
I have faced a problem like this,can you help me？

 18         clean_text = clean(row['Text'])
     19         clean_summary = clean(row['Summary'])
---> 20         summaries.append(word_tokenize(clean_summary))
     21         texts.append(word_tokenize(clean_text))


TypeError: expected string or bytes-like object

**Comment by 1848798517** [comment]
Wheather can I use other datasets which is not csvfile?And can i make this system produce an abstraction summarization of a passage?

**Comment by JRC1995** [comment]
> TypeError: expected string or bytes-like object

I assume you are on python 3?

The issue is in this: filter(lambda x: x in printable, text)
This doesn't return the same format in python 3 as it did in python 2.

I don't remember exactly what to do to convert the return of filter to a string. You can try to google it.

But perhaps this may work; not sure:

return "".join([char for char in text if char not in printable])

if nothing works, just ignore filter, and simply do "return text"; it probably doesn't matter here.

**Comment by JRC1995** [comment]
> Wheather can I use other datasets which is not csvfile?And can i make this system produce an abstraction summarization of a passage?

Yes you can use other formats. Just change the code for data processing accordingly in https://github.com/JRC1995/Abstractive-Summarization/blob/master/Data%20Pre-processing.ipynb

The dataset is only for training/testing though. For predictions you would want to include some other data and run the trained model on it. (you probably have to add extra code for predictions)

**Comment by glitterzhang** [comment]
fixed by following code with assign encoding='utf—8'
with open('glove.6B.100d.txt','r'**,encoding='utf—8'**) as glove: #Read in gbk encoding
    for line in glove.readlines():
        line = list(line.split())
