### ISSUE TITLE
where does the abstraction come from?

### ISSUE THREAD

**Issue by bhomass** [JRC1995/Abstractive-Summarization#12]
Hi I looked at the amazon fine food reviews data. It doesn't seem the review articles are accompanied by summaries. Are they?

Is the abstractive summary part based on any paper, such as Abigail see's pointer-generator? I only see references to lstm papers. 

There is no mention of how you dealt with OOV words. Can you explain how you handled that?

**Comment by JRC1995** [comment]
> It doesn't seem the review articles are accompanied by summaries. Are they?

They are. Check data column descriptions:
https://www.kaggle.com/snap/amazon-fine-food-reviews#Reviews.cs

> **Summary** Brief summary of the review
>  **Text**  Text of the review

> Is the abstractive summary part based on any paper, such as Abigail see's pointer-generator? I only see references to lstm papers.

 It's a basic LSTM based encoder-decoder architecturer with (local) attention. I haven't used any pointer or copy mechanism. It does also have residual recurrent attention (RRA) or something named like that (there should be references to the papers in the notebook) but I am suspicious of that mechanism now a days. 

> There is no mention of how you dealt with OOV words. Can you explain how you handled that?

They are just replaced by a special tag '<UNK>' or something like that. Pointer mechanism is a better way to deal with OOV words that appears in source text, but I didn't know of Pointer mechanism when I initially created the repo.
