### ISSUE TITLE
Don't know where to get these files

### ISSUE THREAD

**Issue by jenigma** [JRC1995/Abstractive-Summarization#2]
Please tell me from where I can get these files:

vec_summaries
vec_texts
vocab_limit
embd_limit

Thanks!  I'm really eager to test this fully...

**Comment by JRC1995** [comment]
@jenigma Check Data Pre-processing.ipynb. First, you will need "glove.6B.50d.txt" which can be  downloaded from https://nlp.stanford.edu/projects/glove/

(I think that txt file I used was inside glove.6B.zip which is available in the link I shared)

Next simply execute the code in "[Data Pre-processing.ipynb](https://github.com/JRC1995/Abstractive-Summarization/blob/master/Data%20Pre-processing.ipynb)". If all goes well those files will be created as a result (of execution).
