### ISSUE TITLE
 embedding = np.asarray(embd)  return array(a, dtype, copy=False, order=order) MemoryError

### ISSUE THREAD

**Issue by ChelakaFernando** [JRC1995/Abstractive-Summarization#6]
I'm using python 3.4 and i get a memory error.when i include a parameter as dtype='object' I'm not able to get the word-tokenize correct.
I get this error:for match in self._lang_vars.period_context_re().finditer(text):
TypeError: expected string or bytes-like object

**Comment by JRC1995** [comment]
Have you tried something like this?
>embedding = np.asarray(embd, dtype=np.float32)
